### PR TITLE
fix(333) permits display of panel over layer panel

### PR DESCRIPTION
**Pull request by Pewillia**
closes(333)

---
This change is [Reviewable](https://reviewable.io/reviews/fgpv-vpgf/contributed-plugins/336)

### CODE REVIEW

**Review by jolevesq — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/fgpv-vpgf/contributed-plugins/336)* status: all files reviewed, 1 unresolved discussion (waiting on @Pewillia)

___
*[thematic-slider/src/slider-panel.ts, line 104 at r1](https://reviewable.io/reviews/fgpv-vpgf/contributed-plugins/336#-MpDFLYj6kID95Ozz6zr:-MpDFLYj6kID95Ozz6zs:btq66kp) ([raw file](https://github.com/fgpv-vpgf/contributed-plugins/blob/799a30ea71321ac958a643ff802edd180f40d950/thematic-slider/src/slider-panel.ts#L104)):*
> ```XML
>         // permits display of thematic panel over layers panel
>         let closeBtn = this._panelSlider.header.closeButton;
>         closeBtn = this._panelSlider.header.closeButton.css('visibility','hidden');
> ```

Space after ,

**Review by Pewillia — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/fgpv-vpgf/contributed-plugins/336)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @jolevesq)

___
*[thematic-slider/src/slider-panel.ts, line 104 at r1](https://reviewable.io/reviews/fgpv-vpgf/contributed-plugins/336#-MpDFLYj6kID95Ozz6zr:-MpDXSPP305o6WNs-JjT:b-896fix) ([raw file](https://github.com/fgpv-vpgf/contributed-plugins/blob/799a30ea71321ac958a643ff802edd180f40d950/thematic-slider/src/slider-panel.ts#L104)):*
<details><summary><i>Previously, jolevesq (Johann Levesque) wrote…</i></summary><blockquote>

Space after ,
</blockquote></details>

Done.

**Review by jolevesq — COMMENTED** [review]
If I close the slider, open the legend and repoen the slider. It is under the legend. CAn you modify the z-index value to solve.

> *[Reviewable](https://reviewable.io/reviews/fgpv-vpgf/contributed-plugins/336#-:-MpDXnKDALO8N8yqYqjb:b-e3j6vu)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @jolevesq)

**Review by jolevesq — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/fgpv-vpgf/contributed-plugins/336#-:-MpMWSCQ9FMF2CowDYRX:bnfp4nl)* status: 0 of 1 files reviewed, all discussions resolved (waiting on @jolevesq)

**Review by jolevesq — APPROVED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/fgpv-vpgf/contributed-plugins/336)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @Pewillia)

**Pull request merged**
