### PR TITLE
fix(356) add  dates in YYYY format

### PR DESCRIPTION
**Pull request by Pewillia**
closes(356)

---
This change is [Reviewable](https://reviewable.io/reviews/fgpv-vpgf/contributed-plugins/436)

### CODE REVIEW

**Review by jolevesq — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/fgpv-vpgf/contributed-plugins/436)* status: 0 of 5 files reviewed, 2 unresolved discussions (waiting on @jolevesq and @Pewillia)

___
*[`chart/src/chart-loader.ts` line 496 at r1](https://reviewable.io/reviews/fgpv-vpgf/contributed-plugins/436#-N88o8TY7qOoDFR37D-l:-N88o8TY7qOoDFR37D-m:b-o60oc) ([raw file](https://github.com/fgpv-vpgf/contributed-plugins/blob/c84ecad88a4445c010f801e229c7518b483054a5/chart/src/chart-loader.ts#L496)):*
> ```XML
>                             let parseCombValues = parse.replace(new RegExp(data.regex, 'g'), '*').split('*').filter(Boolean);
>                             let numberPattern = /\d+/g;
>                             parsed.isDateTimeObjForXAxis = (parseCombValues.filter(q=>{
> ```

Why do you removed isDateTimeObjForXAxis? It is used in other places in the code. Can this trigger side effects?
___
*[`chart/src/chart-parser.ts` line 152 at r1](https://reviewable.io/reviews/fgpv-vpgf/contributed-plugins/436#-N88oisP8ipPC1tVNYuD:-N88oisP8ipPC1tVNYuE:b-7wm6e6) ([raw file](https://github.com/fgpv-vpgf/contributed-plugins/blob/aa8da50c1bad58b5ef4dd9c55daed040778ba3f4/chart/src/chart-parser.ts#L152)):*
> ```XML
>                     values.push(`(${(feat.attributes[layerConfig.data[index].date])},${feat.attributes[layerConfig.data[index].measure]})`)
>             else 
>                     values.push(`(${new Date(feat.attributes[layerConfig.data[index].date]).toJSON()},${feat.attributes[layerConfig.data[index].measure]})`);   
> ```

Remove trailing white space

**Comment by Pewillia** [comment]
I tested it with every test file and no side effects. If iI don't do this test no chart is displayed at all.                       

   if (parseCombValues.includes("T")) {
                                parsed.isDateTimeObjForXAxis = (parseCombValues.filter(q => {
                                    let time: any = parseInt(q.split('T')[1].split(data.split)[0].match(numberPattern).join(''));
                                    if (time > 0) {
                                        return true;
                                    }
                                })).length > 0;

**Review by jolevesq — COMMENTED** [review]
:lgtm: 

> *[Reviewable](https://reviewable.io/reviews/fgpv-vpgf/contributed-plugins/436#-:-N89uWse3Xflax1D6wxy:bg7igkv)* status: 0 of 5 files reviewed, all discussions resolved (waiting on @jolevesq)

**Review by jolevesq — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/fgpv-vpgf/contributed-plugins/436#-:-N89ub0H3GZOrFGcIhSl:bnfp4nl)* status: 0 of 5 files reviewed, all discussions resolved (waiting on @jolevesq)

**Review by jolevesq — APPROVED** [review]
> Reviewed 5 of 5 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/fgpv-vpgf/contributed-plugins/436)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @Pewillia)

**Pull request merged**
