### PR TITLE
feat(thematic): Add details panel and legend

### LINKED ISSUE #85: Add legend to thematic slider
Add a legend to the thematic slider. Add a legend section. this section may have the same image for all the slider or change with the active slide. At first do it from an image inside the configuration file. In a second phase the legend may be created automatically from the layer.

### PR DESCRIPTION
**Pull request by jolevesq**
Closes #85

Take a look at to see it in action

---
This change is [Reviewable](https://reviewable.io/reviews/fgpv-vpgf/contributed-plugins/90)

### CODE REVIEW

**Review by jolevesq — COMMENTED** [review]
https://jolevesq.github.io/contributed-plugins/thematic-slider/samples/thematic-slider-index.html?sample=6

> *[Reviewable](https://reviewable.io/reviews/fgpv-vpgf/contributed-plugins/90#-:-MHHfTFACmX4x7GtwRNu:b-79qfaf)* status: 0 of 13 files reviewed, all discussions resolved (waiting on @aparujan)

**Comment by aparujan** [comment]
___
*[thematic-slider/src/samples/thematic-slider-index.html, line 33 at r1](https://reviewable.io/reviews/fgpv-vpgf/contributed-plugins/90#-MHHjciJ5QO51O65mgXf:-MHHjciJ5QO51O65mgXg:b13pkp2) ([raw file](https://github.com/fgpv-vpgf/contributed-plugins/blob/6090464c5e229ea27716d9ff2e3ce931f5fd22eb/thematic-slider/src/samples/thematic-slider-index.html#L33)):*
> ```HTML
>                     <option value="thematic-slider-naked-config.json">04. Autorun no controls</option>
>                     <option value="thematic-slider-wms-config.json">05. WMS</option>
>                     <option value="thematic-slider-custom-legend-config.json">05. Custom Legend</option>
> ```

@jolevesq place #6 for Custom Legend, as #5 is already assigned to WMS above.

**Review by jolevesq — COMMENTED** [review]
> Reviewed 1 of 13 files at r1.
> *[Reviewable](https://reviewable.io/reviews/fgpv-vpgf/contributed-plugins/90)* status: 1 of 13 files reviewed, 2 unresolved discussions (waiting on @aparujan and @jolevesq)

___
*[thematic-slider/README.md, line 25 at r1](https://reviewable.io/reviews/fgpv-vpgf/contributed-plugins/90#-MHHl9cjCyPBRSGaQ0fa:-MHHl9cjCyPBRSGaQ0fb:b-c2r3v3) ([raw file](https://github.com/fgpv-vpgf/contributed-plugins/blob/6090464c5e229ea27716d9ff2e3ce931f5fd22eb/thematic-slider/README.md#L25)):*
> ```Markdown
>                 "image": {
>                   "url": "http://...",
>                   "width: 200,
> ```

Add double quote

**Comment by aparujan** [comment]
___
*[thematic-slider/README.md, line 40 at r1](https://reviewable.io/reviews/fgpv-vpgf/contributed-plugins/90#-MHHlkcj5bn7L2W5tR6A:-MHHlkck1eLilqOtnMkv:b-bhckx4) ([raw file](https://github.com/fgpv-vpgf/contributed-plugins/blob/6090464c5e229ea27716d9ff2e3ce931f5fd22eb/thematic-slider/README.md#L40)):*
> ```Markdown
>                 "image": {
>                   "url": "http://...",
>                   "width: 200,
> ```

Add quotation mark after the width

**Comment by aparujan** [comment]
___
*[thematic-slider/README.md, line 55 at r1](https://reviewable.io/reviews/fgpv-vpgf/contributed-plugins/90#-MHHq9Zj3t1fsn27c9Bz:-MHHq9Zj3t1fsn27c9C-:b-bhckx4) ([raw file](https://github.com/fgpv-vpgf/contributed-plugins/blob/6090464c5e229ea27716d9ff2e3ce931f5fd22eb/thematic-slider/README.md#L55)):*
> ```Markdown
>                 "image": {
>                   "url": "http://...",
>                   "width: 200,
> ```

Add quotation mark after the width

**Comment by aparujan** [comment]
___
*[thematic-slider/README.md, line 70 at r1](https://reviewable.io/reviews/fgpv-vpgf/contributed-plugins/90#-MHHqBy982k94_vgSNd3:-MHHqBy982k94_vgSNd4:b-bhckx4) ([raw file](https://github.com/fgpv-vpgf/contributed-plugins/blob/6090464c5e229ea27716d9ff2e3ce931f5fd22eb/thematic-slider/README.md#L70)):*
> ```Markdown
>                 "image": {
>                   "url": "http://...",
>                   "width: 200,
> ```

Add quotation mark after the width

**Comment by aparujan** [comment]
___
*[thematic-slider/src/slider-panel.ts, line 78 at r1](https://reviewable.io/reviews/fgpv-vpgf/contributed-plugins/90#-MHHr8d03RC_H3feLYQ_:-MHHr8d03RC_H3feLYQa:bb8ze1b) ([raw file](https://github.com/fgpv-vpgf/contributed-plugins/blob/6090464c5e229ea27716d9ff2e3ce931f5fd22eb/thematic-slider/src/slider-panel.ts#L78)):*
> ```XML
>         this._panelSlider.body = SLIDER_TEMPLATE;
> 
>         // set layers fomr config
> ```

Typo, "from" config

**Comment by aparujan** [comment]
___
*[thematic-slider/src/slider-panel.ts, line 176 at r1](https://reviewable.io/reviews/fgpv-vpgf/contributed-plugins/90#-MHHsxxACcRX7p5meUOd:-MHHsxxACcRX7p5meUOe:bi252cr) ([raw file](https://github.com/fgpv-vpgf/contributed-plugins/blob/6090464c5e229ea27716d9ff2e3ce931f5fd22eb/thematic-slider/src/slider-panel.ts#L176)):*
> ```XML
>             }
> 
>             stack += `<div class="rv-thslider-symbol" style="min-height:${image.height}px">
> ```

Possible typo: apostrophe after stack +=

**Comment by aparujan** [comment]
___
*[thematic-slider/src/slider-panel.ts, line 179 at r1](https://reviewable.io/reviews/fgpv-vpgf/contributed-plugins/90#-MHHt8ze6d7sx6NH4imF:-MHHt8ze6d7sx6NH4imG:b-xpk9rs) ([raw file](https://github.com/fgpv-vpgf/contributed-plugins/blob/6090464c5e229ea27716d9ff2e3ce931f5fd22eb/thematic-slider/src/slider-panel.ts#L179)):*
> ```XML
>                         sd-logo
>                         <span>${(entry as any).label}</span>
>                     </div>`
> ```

Possible typo: apostrophe after <div>

**Comment by aparujan** [comment]
___
*[thematic-slider/src/slider-panel.ts, line 227 at r1](https://reviewable.io/reviews/fgpv-vpgf/contributed-plugins/90#-MHHtuXiC-tfnlqilDUt:-MHHtuXiC-tfnlqilDUu:b20aw99) ([raw file](https://github.com/fgpv-vpgf/contributed-plugins/blob/6090464c5e229ea27716d9ff2e3ce931f5fd22eb/thematic-slider/src/slider-panel.ts#L227)):*
> ```XML
>             const size = doc.querySelector('svg').getAttribute('viewBox').split(' ').slice(2).map((x) => { return parseInt(x, 10); })
> 
>             legend += `<div class="rv-thslider-symbol" style="min-height:${size[1]}px">
> ```

Apostrohpe after legend += might need to be changed to a vertical tick

**Comment by aparujan** [comment]
___
*[thematic-slider/src/slider-panel.ts, line 230 at r1](https://reviewable.io/reviews/fgpv-vpgf/contributed-plugins/90#-MHHu6eo4it_WD5JRvHs:-MHHu6ep0gyDa7vnfvn9:b-een74f) ([raw file](https://github.com/fgpv-vpgf/contributed-plugins/blob/6090464c5e229ea27716d9ff2e3ce931f5fd22eb/thematic-slider/src/slider-panel.ts#L230)):*
> ```XML
>                             ${[svg.svgcode.slice(0, 5), `style="min-width:${size[0]}px;min-height:${size[1]}px"`, svg.svgcode.slice(4)].join('')}
>                             <span>${svg.name}</span>
>                         </div>`
> ```

Apostrohpe after </div> need to be changed to a vertical tick

**Comment by aparujan** [comment]
___
*[thematic-slider/src/template.ts, line 2 at r1](https://reviewable.io/reviews/fgpv-vpgf/contributed-plugins/90#-MHHuHtH7JeMe-8gRYrS:-MHHuHtH7JeMe-8gRYrT:bo60c6d) ([raw file](https://github.com/fgpv-vpgf/contributed-plugins/blob/6090464c5e229ea27716d9ff2e3ce931f5fd22eb/thematic-slider/src/template.ts#L2)):*
> ```XML
> // panels templates
> export const SLIDER_TEMPLATE = `
> ```

Apostrohpe after = might need to be changed to a vertical tick

**Comment by aparujan** [comment]
___
*[thematic-slider/src/template.ts, line 4 at r1](https://reviewable.io/reviews/fgpv-vpgf/contributed-plugins/90#-MHHuM281KEDOqe339JR:-MHHuM281KEDOqe339JS:b-uyc908) ([raw file](https://github.com/fgpv-vpgf/contributed-plugins/blob/6090464c5e229ea27716d9ff2e3ce931f5fd22eb/thematic-slider/src/template.ts#L4)):*
> ```XML
> export const SLIDER_TEMPLATE = `
> <div rv-focus-member class="rv-thematic-slider">
> </div>`;
> ```

Apostrohpe after </div> might need to be changed to a vertical tick

**Comment by aparujan** [comment]
___
*[thematic-slider/src/template.ts, line 7 at r1](https://reviewable.io/reviews/fgpv-vpgf/contributed-plugins/90#-MHHuVE58As6tPa3VYt1:-MHHuVE58As6tPa3VYt2:bo60c6d) ([raw file](https://github.com/fgpv-vpgf/contributed-plugins/blob/6090464c5e229ea27716d9ff2e3ce931f5fd22eb/thematic-slider/src/template.ts#L7)):*
> ```XML
> 
> // description controller template
> export const DESCRIPTION_TEMPLATE = `
> ```

Apostrohpe after = might need to be changed to a vertical tick

**Comment by aparujan** [comment]
___
*[thematic-slider/src/template.ts, line 16 at r1](https://reviewable.io/reviews/fgpv-vpgf/contributed-plugins/90#-MHHudbwDEnJSDHY3n2J:-MHHudbx2sJor5sdRKYr:b-415yqk) ([raw file](https://github.com/fgpv-vpgf/contributed-plugins/blob/6090464c5e229ea27716d9ff2e3ce931f5fd22eb/thematic-slider/src/template.ts#L16)):*
> ```XML
>         <md-tooltip md-direction="top">{{ ctrl.isLegend ? 'toc.label.group.collapse' : 'toc.label.group.expand' | translate }}</md-tooltip>
>     </md-button>
>     
> ```

Trailing whitespace

**Comment by aparujan** [comment]
___
*[thematic-slider/src/template.ts, line 23 at r1](https://reviewable.io/reviews/fgpv-vpgf/contributed-plugins/90#-MHHulB03vO-APAJsp9V:-MHHulB03vO-APAJsp9W:b-uyc908) ([raw file](https://github.com/fgpv-vpgf/contributed-plugins/blob/6090464c5e229ea27716d9ff2e3ce931f5fd22eb/thematic-slider/src/template.ts#L23)):*
> ```XML
>     <div class="rv-thslider-desc">{{ ctrl.description }}</div>
>     <span class="rv-thslider-index">{{ ctrl.index }}</span>
> </div>`;
> ```

Apostrohpe after </div> might need to be changed to a vertical tick

**Comment by aparujan** [comment]
___
*[thematic-slider/src/samples/thematic-slider-custom-legend-config.json, line 101 at r1](https://reviewable.io/reviews/fgpv-vpgf/contributed-plugins/90#-MHHvQOk2BVocj7typX8:-MHHvQOk2BVocj7typX9:b-2aoe7e) ([raw file](https://github.com/fgpv-vpgf/contributed-plugins/blob/6090464c5e229ea27716d9ff2e3ce931f5fd22eb/thematic-slider/src/samples/thematic-slider-custom-legend-config.json#L101)):*
> ```JSON
>         {
>           "id": "1",
>           "name": "etroleum",
> ```

Typo: missing P for the word Petroleum

**Comment by aparujan** [comment]
___
*[thematic-slider/src/samples/thematic-slider-custom-legend-config.json, line 95 at r1](https://reviewable.io/reviews/fgpv-vpgf/contributed-plugins/90#-MHHvXgc3JFaMRbo5zbC:-MHHvXgc3JFaMRbo5zbD:b-r7x1qr) ([raw file](https://github.com/fgpv-vpgf/contributed-plugins/blob/6090464c5e229ea27716d9ff2e3ce931f5fd22eb/thematic-slider/src/samples/thematic-slider-custom-legend-config.json#L95)):*
> ```JSON
>         {
>           "id": "0",
>           "name": "hydrop",
> ```

Possible typo: "hydro" or "hydro power"?

**Comment by aparujan** [comment]
___
*[thematic-slider/src/slider-panel.ts, line 177 at r1](https://reviewable.io/reviews/fgpv-vpgf/contributed-plugins/90#-MHI-3oR9On8PoXPckXQ:-MHI-3oR9On8PoXPckXR:bpfmmn4) ([raw file](https://github.com/fgpv-vpgf/contributed-plugins/blob/6090464c5e229ea27716d9ff2e3ce931f5fd22eb/thematic-slider/src/slider-panel.ts#L177)):*
> ```XML
> 
>             stack += `<div class="rv-thslider-symbol" style="min-height:${image.height}px">
>                         sd-logo
> ```

Alt text and Title: perhaps using an English & French phrase to be bilingual.

**Review by aparujan — CHANGES_REQUESTED** [review]
> Reviewed 12 of 13 files at r1.
> *[Reviewable](https://reviewable.io/reviews/fgpv-vpgf/contributed-plugins/90)* status: all files reviewed, 24 unresolved discussions (waiting on @jolevesq)

___
*[thematic-slider/src/slider-panel.ts, line 92 at r1](https://reviewable.io/reviews/fgpv-vpgf/contributed-plugins/90#-MHHrRtp7yO8byO_Th9j:-MHHrRtp7yO8byO_Th9k:b6fz40e) ([raw file](https://github.com/fgpv-vpgf/contributed-plugins/blob/6090464c5e229ea27716d9ff2e3ce931f5fd22eb/thematic-slider/src/slider-panel.ts#L92)):*
> ```XML
> 
>                 // init panel title and description with the first element
>                 // apply a time out with 500, if not, the legend section is not aviallable
> ```

Typo, "timeout" is one word.
___
*[thematic-slider/src/slider-panel.ts, line 158 at r1](https://reviewable.io/reviews/fgpv-vpgf/contributed-plugins/90#-MHHsT7h8sRJKBjSgQgt:-MHHsT7h8sRJKBjSgQgu:bt4eol2) ([raw file](https://github.com/fgpv-vpgf/contributed-plugins/blob/6090464c5e229ea27716d9ff2e3ce931f5fd22eb/thematic-slider/src/slider-panel.ts#L158)):*
> ```XML
> 
>         // set panel content, it will create the legend section
>         SliderPanel.setDescription({ desc: this.active.description, index: `${this._index + 1}/${this._layers.length}` });
> ```

Possible typo: index: there is an apostrophe, but it isn't a normal one, like a verticle tick, it is on an angle. It might not affect the code though. This also occurs at the end of the line too.
___
*[thematic-slider/src/slider-panel.ts, line 198 at r1](https://reviewable.io/reviews/fgpv-vpgf/contributed-plugins/90#-MHHtHcZ3-eJsB_WBPQe:-MHHtHcZ3-eJsB_WBPQf:b-o1bblj) ([raw file](https://github.com/fgpv-vpgf/contributed-plugins/blob/6090464c5e229ea27716d9ff2e3ce931f5fd22eb/thematic-slider/src/slider-panel.ts#L198)):*
> ```XML
>         });
> 
>         // Check block type anfd loop trought nodes
> ```

Typos: "and" also "through"
___
*[thematic-slider/src/samples/thematic-slider-loop-config.json, line 286 at r1](https://reviewable.io/reviews/fgpv-vpgf/contributed-plugins/90#-MHHws80EgUUbihrMI42:-MHHws80EgUUbihrMI43:b-e77o6m) ([raw file](https://github.com/fgpv-vpgf/contributed-plugins/blob/6090464c5e229ea27716d9ff2e3ce931f5fd22eb/thematic-slider/src/samples/thematic-slider-loop-config.json#L286)):*
> ```JSON
>             "id": "1",
>             "duration": 3000,
>             "title": "petroleum",
> ```

Perhaps a capital P?
___
*[thematic-slider/src/samples/thematic-slider-naked-config.json, line 95 at r1](https://reviewable.io/reviews/fgpv-vpgf/contributed-plugins/90#-MHHwkg0Aiy_5oN4J6Bv:-MHHwkg0Aiy_5oN4J6Bw:b-r7x1qr) ([raw file](https://github.com/fgpv-vpgf/contributed-plugins/blob/6090464c5e229ea27716d9ff2e3ce931f5fd22eb/thematic-slider/src/samples/thematic-slider-naked-config.json#L95)):*
> ```JSON
>         {
>           "id": "0",
>           "name": "hydrop",
> ```

Possible typo: "hydro" or "hydro power"?
___
*[thematic-slider/src/samples/thematic-slider-naked-config.json, line 101 at r1](https://reviewable.io/reviews/fgpv-vpgf/contributed-plugins/90#-MHHwxGk3DQ4NPItBv5X:-MHHwxGk3DQ4NPItBv5Y:bmz3vnr) ([raw file](https://github.com/fgpv-vpgf/contributed-plugins/blob/6090464c5e229ea27716d9ff2e3ce931f5fd22eb/thematic-slider/src/samples/thematic-slider-naked-config.json#L101)):*
> ```JSON
>         {
>           "id": "1",
>           "name": "etroleum",
> ```

Typo: Missing P

**Review by jolevesq — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/fgpv-vpgf/contributed-plugins/90)* status: all files reviewed, 23 unresolved discussions (waiting on @aparujan)

___
*[thematic-slider/README.md, line 25 at r1](https://reviewable.io/reviews/fgpv-vpgf/contributed-plugins/90#-MHHl9cjCyPBRSGaQ0fa:-MHI2K3o-HrdNzycTWtB:bs7wumb) ([raw file](https://github.com/fgpv-vpgf/contributed-plugins/blob/6090464c5e229ea27716d9ff2e3ce931f5fd22eb/thematic-slider/README.md#L25)):*
<details><summary><i>Previously, jolevesq (Johann Levesque) wrote…</i></summary><blockquote>

Add double quote
</blockquote></details>

Done.
___
*[thematic-slider/README.md, line 40 at r1](https://reviewable.io/reviews/fgpv-vpgf/contributed-plugins/90#-MHHlkcj5bn7L2W5tR6A:-MHI2Lf08d2sILudnj0h:b-896fix) ([raw file](https://github.com/fgpv-vpgf/contributed-plugins/blob/6090464c5e229ea27716d9ff2e3ce931f5fd22eb/thematic-slider/README.md#L40)):*
<details><summary><i>Previously, aparujan (Akhil Parujanwala) wrote…</i></summary><blockquote>

Add quotation mark after the width
</blockquote></details>

Done.
___
*[thematic-slider/README.md, line 55 at r1](https://reviewable.io/reviews/fgpv-vpgf/contributed-plugins/90#-MHHq9Zj3t1fsn27c9Bz:-MHI2PD4-vGpjlV4B8ut:b-896fix) ([raw file](https://github.com/fgpv-vpgf/contributed-plugins/blob/6090464c5e229ea27716d9ff2e3ce931f5fd22eb/thematic-slider/README.md#L55)):*
<details><summary><i>Previously, aparujan (Akhil Parujanwala) wrote…</i></summary><blockquote>

Add quotation mark after the width
</blockquote></details>

Done.
___
*[thematic-slider/README.md, line 70 at r1](https://reviewable.io/reviews/fgpv-vpgf/contributed-plugins/90#-MHHqBy982k94_vgSNd3:-MHI2Pos6ZyCQY-E6czC:b-896fix) ([raw file](https://github.com/fgpv-vpgf/contributed-plugins/blob/6090464c5e229ea27716d9ff2e3ce931f5fd22eb/thematic-slider/README.md#L70)):*
<details><summary><i>Previously, aparujan (Akhil Parujanwala) wrote…</i></summary><blockquote>

Add quotation mark after the width
</blockquote></details>

Done.
___
*[thematic-slider/src/slider-panel.ts, line 78 at r1](https://reviewable.io/reviews/fgpv-vpgf/contributed-plugins/90#-MHHr8d03RC_H3feLYQ_:-MHI2gYxD4H0lq66dhph:b-896fix) ([raw file](https://github.com/fgpv-vpgf/contributed-plugins/blob/6090464c5e229ea27716d9ff2e3ce931f5fd22eb/thematic-slider/src/slider-panel.ts#L78)):*
<details><summary><i>Previously, aparujan (Akhil Parujanwala) wrote…</i></summary><blockquote>

Typo, "from" config
</blockquote></details>

Done.
___
*[thematic-slider/src/slider-panel.ts, line 92 at r1](https://reviewable.io/reviews/fgpv-vpgf/contributed-plugins/90#-MHHrRtp7yO8byO_Th9j:-MHI2nqq73lIOqIxoyqQ:b-896fix) ([raw file](https://github.com/fgpv-vpgf/contributed-plugins/blob/6090464c5e229ea27716d9ff2e3ce931f5fd22eb/thematic-slider/src/slider-panel.ts#L92)):*
<details><summary><i>Previously, aparujan (Akhil Parujanwala) wrote…</i></summary><blockquote>

Typo, "timeout" is one word.
</blockquote></details>

Done.
___
*[thematic-slider/src/slider-panel.ts, line 158 at r1](https://reviewable.io/reviews/fgpv-vpgf/contributed-plugins/90#-MHHsT7h8sRJKBjSgQgt:-MHI2qxmDUxwKlDPWIgK:bfxbqxf) ([raw file](https://github.com/fgpv-vpgf/contributed-plugins/blob/6090464c5e229ea27716d9ff2e3ce931f5fd22eb/thematic-slider/src/slider-panel.ts#L158)):*
<details><summary><i>Previously, aparujan (Akhil Parujanwala) wrote…</i></summary><blockquote>

Possible typo: index: there is an apostrophe, but it isn't a normal one, like a verticle tick, it is on an angle. It might not affect the code though. This also occurs at the end of the line too.
</blockquote></details>

This the way we aggregate string in the latest JavaScript standard, it is call string literal. Instead of doing this - let a = 'test' + value you do let a = `test${value}`. You put the variable in ${} 
___
*[thematic-slider/src/slider-panel.ts, line 176 at r1](https://reviewable.io/reviews/fgpv-vpgf/contributed-plugins/90#-MHHsxxACcRX7p5meUOd:-MHI3c2FAG98rtZJoKW8:b-s92nmq) ([raw file](https://github.com/fgpv-vpgf/contributed-plugins/blob/6090464c5e229ea27716d9ff2e3ce931f5fd22eb/thematic-slider/src/slider-panel.ts#L176)):*
<details><summary><i>Previously, aparujan (Akhil Parujanwala) wrote…</i></summary><blockquote>

Possible typo: apostrophe after stack +=
</blockquote></details>

It is a way to contact a string to an existing string. we can use string.concat(string2, string3[, ..., stringN]) as well but += is shorter
___
*[thematic-slider/src/slider-panel.ts, line 177 at r1](https://reviewable.io/reviews/fgpv-vpgf/contributed-plugins/90#-MHI-3oR9On8PoXPckXQ:-MHI5lan1obUDDoVuaFF:b-896fix) ([raw file](https://github.com/fgpv-vpgf/contributed-plugins/blob/6090464c5e229ea27716d9ff2e3ce931f5fd22eb/thematic-slider/src/slider-panel.ts#L177)):*
<details><summary><i>Previously, aparujan (Akhil Parujanwala) wrote…</i></summary><blockquote>

Alt text and Title: perhaps using an English & French phrase to be bilingual.
</blockquote></details>

Done.
___
*[thematic-slider/src/slider-panel.ts, line 179 at r1](https://reviewable.io/reviews/fgpv-vpgf/contributed-plugins/90#-MHHt8ze6d7sx6NH4imF:-MHI5m3y7TYwESzBIsZa:be2gbnj) ([raw file](https://github.com/fgpv-vpgf/contributed-plugins/blob/6090464c5e229ea27716d9ff2e3ce931f5fd22eb/thematic-slider/src/slider-panel.ts#L179)):*
<details><summary><i>Previously, aparujan (Akhil Parujanwala) wrote…</i></summary><blockquote>

Possible typo: apostrophe after <div>
</blockquote></details>

End of string literal
___
*[thematic-slider/src/slider-panel.ts, line 198 at r1](https://reviewable.io/reviews/fgpv-vpgf/contributed-plugins/90#-MHHtHcZ3-eJsB_WBPQe:-MHI5vDi8dQDpNa-Dv6P:b-896fix) ([raw file](https://github.com/fgpv-vpgf/contributed-plugins/blob/6090464c5e229ea27716d9ff2e3ce931f5fd22eb/thematic-slider/src/slider-panel.ts#L198)):*
<details><summary><i>Previously, aparujan (Akhil Parujanwala) wrote…</i></summary><blockquote>

Typos: "and" also "through"
</blockquote></details>

Done.
___
*[thematic-slider/src/slider-panel.ts, line 227 at r1](https://reviewable.io/reviews/fgpv-vpgf/contributed-plugins/90#-MHHtuXiC-tfnlqilDUt:-MHI5y3gAl_njOFMb5PP:beig0ed) ([raw file](https://github.com/fgpv-vpgf/contributed-plugins/blob/6090464c5e229ea27716d9ff2e3ce931f5fd22eb/thematic-slider/src/slider-panel.ts#L227)):*
<details><summary><i>Previously, aparujan (Akhil Parujanwala) wrote…</i></summary><blockquote>

Apostrohpe after legend += might need to be changed to a vertical tick
</blockquote></details>

String literal
___
*[thematic-slider/src/slider-panel.ts, line 230 at r1](https://reviewable.io/reviews/fgpv-vpgf/contributed-plugins/90#-MHHu6eo4it_WD5JRvHs:-MHI60QbAZWT6vAfaq4r:beig0ed) ([raw file](https://github.com/fgpv-vpgf/contributed-plugins/blob/6090464c5e229ea27716d9ff2e3ce931f5fd22eb/thematic-slider/src/slider-panel.ts#L230)):*
<details><summary><i>Previously, aparujan (Akhil Parujanwala) wrote…</i></summary><blockquote>

Apostrohpe after </div> need to be changed to a vertical tick
</blockquote></details>

String literal
___
*[thematic-slider/src/template.ts, line 2 at r1](https://reviewable.io/reviews/fgpv-vpgf/contributed-plugins/90#-MHHuHtH7JeMe-8gRYrS:-MHI62t1A9A8shRhk9bF:beig0ed) ([raw file](https://github.com/fgpv-vpgf/contributed-plugins/blob/6090464c5e229ea27716d9ff2e3ce931f5fd22eb/thematic-slider/src/template.ts#L2)):*
<details><summary><i>Previously, aparujan (Akhil Parujanwala) wrote…</i></summary><blockquote>

Apostrohpe after = might need to be changed to a vertical tick
</blockquote></details>

String literal
___
*[thematic-slider/src/template.ts, line 4 at r1](https://reviewable.io/reviews/fgpv-vpgf/contributed-plugins/90#-MHHuM281KEDOqe339JR:-MHI65P6Aac6_1lGo9M9:beig0ed) ([raw file](https://github.com/fgpv-vpgf/contributed-plugins/blob/6090464c5e229ea27716d9ff2e3ce931f5fd22eb/thematic-slider/src/template.ts#L4)):*
<details><summary><i>Previously, aparujan (Akhil Parujanwala) wrote…</i></summary><blockquote>

Apostrohpe after </div> might need to be changed to a vertical tick
</blockquote></details>

String literal
___
*[thematic-slider/src/template.ts, line 7 at r1](https://reviewable.io/reviews/fgpv-vpgf/contributed-plugins/90#-MHHuVE58As6tPa3VYt1:-MHI67DP5t5rtJR3HdtS:beig0ed) ([raw file](https://github.com/fgpv-vpgf/contributed-plugins/blob/6090464c5e229ea27716d9ff2e3ce931f5fd22eb/thematic-slider/src/template.ts#L7)):*
<details><summary><i>Previously, aparujan (Akhil Parujanwala) wrote…</i></summary><blockquote>

Apostrohpe after = might need to be changed to a vertical tick
</blockquote></details>

String literal
___
*[thematic-slider/src/template.ts, line 16 at r1](https://reviewable.io/reviews/fgpv-vpgf/contributed-plugins/90#-MHHudbwDEnJSDHY3n2J:-MHI6CCs6hcKjFftUPZs:b-896fix) ([raw file](https://github.com/fgpv-vpgf/contributed-plugins/blob/6090464c5e229ea27716d9ff2e3ce931f5fd22eb/thematic-slider/src/template.ts#L16)):*
<details><summary><i>Previously, aparujan (Akhil Parujanwala) wrote…</i></summary><blockquote>

Trailing whitespace 
</blockquote></details>

Done.
___
*[thematic-slider/src/template.ts, line 23 at r1](https://reviewable.io/reviews/fgpv-vpgf/contributed-plugins/90#-MHHulB03vO-APAJsp9V:-MHI6Rfc90JXmSQRuWBx:beig0ed) ([raw file](https://github.com/fgpv-vpgf/contributed-plugins/blob/6090464c5e229ea27716d9ff2e3ce931f5fd22eb/thematic-slider/src/template.ts#L23)):*
<details><summary><i>Previously, aparujan (Akhil Parujanwala) wrote…</i></summary><blockquote>

Apostrohpe after </div> might need to be changed to a vertical tick
</blockquote></details>

String literal
___
*[thematic-slider/src/samples/thematic-slider-custom-legend-config.json, line 95 at r1](https://reviewable.io/reviews/fgpv-vpgf/contributed-plugins/90#-MHHvXgc3JFaMRbo5zbC:-MHI6rvc-i6dQag7Ew3n:b-896fix) ([raw file](https://github.com/fgpv-vpgf/contributed-plugins/blob/6090464c5e229ea27716d9ff2e3ce931f5fd22eb/thematic-slider/src/samples/thematic-slider-custom-legend-config.json#L95)):*
<details><summary><i>Previously, aparujan (Akhil Parujanwala) wrote…</i></summary><blockquote>

Possible typo: "hydro" or "hydro power"?
</blockquote></details>

Done.
___
*[thematic-slider/src/samples/thematic-slider-custom-legend-config.json, line 101 at r1](https://reviewable.io/reviews/fgpv-vpgf/contributed-plugins/90#-MHHvQOk2BVocj7typX8:-MHI6sa75ZzLr-8aQo2V:b-896fix) ([raw file](https://github.com/fgpv-vpgf/contributed-plugins/blob/6090464c5e229ea27716d9ff2e3ce931f5fd22eb/thematic-slider/src/samples/thematic-slider-custom-legend-config.json#L101)):*
<details><summary><i>Previously, aparujan (Akhil Parujanwala) wrote…</i></summary><blockquote>

Typo: missing P for the word Petroleum
</blockquote></details>

Done.
___
*[thematic-slider/src/samples/thematic-slider-index.html, line 33 at r1](https://reviewable.io/reviews/fgpv-vpgf/contributed-plugins/90#-MHHjciJ5QO51O65mgXf:-MHI7nqG2r0AoGXcKq5r:b-896fix) ([raw file](https://github.com/fgpv-vpgf/contributed-plugins/blob/6090464c5e229ea27716d9ff2e3ce931f5fd22eb/thematic-slider/src/samples/thematic-slider-index.html#L33)):*
<details><summary><i>Previously, aparujan (Akhil Parujanwala) wrote…</i></summary><blockquote>

@jolevesq place #6 for Custom Legend, as #5 is already assigned to WMS above.
</blockquote></details>

Done.
___
*[thematic-slider/src/samples/thematic-slider-loop-config.json, line 286 at r1](https://reviewable.io/reviews/fgpv-vpgf/contributed-plugins/90#-MHHws80EgUUbihrMI42:-MHI7gqHBm0b6B6PFEJH:b-896fix) ([raw file](https://github.com/fgpv-vpgf/contributed-plugins/blob/6090464c5e229ea27716d9ff2e3ce931f5fd22eb/thematic-slider/src/samples/thematic-slider-loop-config.json#L286)):*
<details><summary><i>Previously, aparujan (Akhil Parujanwala) wrote…</i></summary><blockquote>

Perhaps a capital P?
</blockquote></details>

Done.
___
*[thematic-slider/src/samples/thematic-slider-naked-config.json, line 95 at r1](https://reviewable.io/reviews/fgpv-vpgf/contributed-plugins/90#-MHHwkg0Aiy_5oN4J6Bv:-MHI7iIG7CxQrCd-7wRy:b-896fix) ([raw file](https://github.com/fgpv-vpgf/contributed-plugins/blob/6090464c5e229ea27716d9ff2e3ce931f5fd22eb/thematic-slider/src/samples/thematic-slider-naked-config.json#L95)):*
<details><summary><i>Previously, aparujan (Akhil Parujanwala) wrote…</i></summary><blockquote>

Possible typo: "hydro" or "hydro power"?
</blockquote></details>

Done.
___
*[thematic-slider/src/samples/thematic-slider-naked-config.json, line 101 at r1](https://reviewable.io/reviews/fgpv-vpgf/contributed-plugins/90#-MHHwxGk3DQ4NPItBv5X:-MHI7j-_5NjKHAxXpIUu:b-896fix) ([raw file](https://github.com/fgpv-vpgf/contributed-plugins/blob/6090464c5e229ea27716d9ff2e3ce931f5fd22eb/thematic-slider/src/samples/thematic-slider-naked-config.json#L101)):*
<details><summary><i>Previously, aparujan (Akhil Parujanwala) wrote…</i></summary><blockquote>

Typo: Missing P
</blockquote></details>

Done.

**Comment by aparujan** [comment]
___
*[thematic-slider/src/samples/thematic-slider-index.html, line 36 at r2](https://reviewable.io/reviews/fgpv-vpgf/contributed-plugins/90#-MHM3P1v1lF4hcECSL4_:-MHM3P1v1lF4hcECSL4a:b-vdcnoh) ([raw file](https://github.com/fgpv-vpgf/contributed-plugins/blob/567942c5949ec9a0fa1b9b3cc7b6f8be961d961f/thematic-slider/src/samples/thematic-slider-index.html#L36)):*
> ```HTML
>                     <option value="thematic-slider-osdp1-config.json">07. OSDP use case 1</option>
>                     <option value="thematic-slider-osdp2-config.json">08. OSDP use case 2</option>
>                     <option value="thematic-slider-osdp3-config.json">09. OSDP use case 3</option>
> ```

For each of the 3 OSDP Use Cases 1, 2, and 3, perhaps putting a small descriptor for developers and users to indicate what the use could will do. This is completely optional .

**Review by aparujan — COMMENTED** [review]
> Reviewed 13 of 13 files at r2.
> *[Reviewable](https://reviewable.io/reviews/fgpv-vpgf/contributed-plugins/90)* status: all files reviewed, 24 unresolved discussions (waiting on @aparujan and @jolevesq)

**Review by aparujan — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/fgpv-vpgf/contributed-plugins/90#-:-MHM5oP805y7hSJEPeMv:bnfp4nl)* status: all files reviewed, 24 unresolved discussions (waiting on @aparujan and @jolevesq)

**Review by aparujan — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/fgpv-vpgf/contributed-plugins/90)* status: :shipit: complete! all files reviewed, all discussions resolved

**Pull request merged**
