### PR TITLE
fix(177): add horizontal swiper

### PR DESCRIPTION
**Pull request by Pewillia**
closes(177)

---
This change is [Reviewable](https://reviewable.io/reviews/fgpv-vpgf/contributed-plugins/191)

### CODE REVIEW

**Review by jolevesq — CHANGES_REQUESTED** [review]
> Reviewed 2 of 4 files at r1.
> *[Reviewable](https://reviewable.io/reviews/fgpv-vpgf/contributed-plugins/191)* status: 2 of 4 files reviewed, 15 unresolved discussions (waiting on @Pewillia)

___
*[swiper/src/index.ts, line 67 at r1](https://reviewable.io/reviews/fgpv-vpgf/contributed-plugins/191#-MZTCPuk25e7QsRjzUkV:-MZTCPul6Zjrm-TVv87P:b-m1cwj2) ([raw file](https://github.com/fgpv-vpgf/contributed-plugins/blob/764039fb8f716463e647fa62d6c3af234d9c995f/swiper/src/index.ts#L67)):*
> ```XML
>         let that = this;
>         swipeWidget.on('load', function() {
>             const item = that.mapApi.mapDiv.find('#rv-swiper-div .'+swipeWidget.type)[0];
> ```

Use string literal `#rv-swiper-div .${swipeWidget.type}`
___
*[swiper/src/index.ts, line 74 at r1](https://reviewable.io/reviews/fgpv-vpgf/contributed-plugins/191#-MZTHxcX00ktcrtOGdY9:-MZTHxcX00ktcrtOGdYA:b7zf2ir) ([raw file](https://github.com/fgpv-vpgf/contributed-plugins/blob/764039fb8f716463e647fa62d6c3af234d9c995f/swiper/src/index.ts#L74)):*
> ```XML
>                  if (swiper.type === 'vertical') {
>                     let value = parseInt(item.style.left);
>                     const width = parseInt(that.mapApi.mapDiv.find('#rv-swiper-div').width()) - 10;    
> ```

Trailing white spaces
___
*[swiper/src/index.ts, line 86 at r1](https://reviewable.io/reviews/fgpv-vpgf/contributed-plugins/191#-MZTI2mg8yhA52sFM-rF:-MZTI2mg8yhA52sFM-rG:bm7rkzu) ([raw file](https://github.com/fgpv-vpgf/contributed-plugins/blob/764039fb8f716463e647fa62d6c3af234d9c995f/swiper/src/index.ts#L86)):*
> ```XML
>                 else if (swiper.type === 'horizontal'){
>                     let value = parseInt(item.style.top);
>                     const heigth = parseInt(that.mapApi.mapDiv.find('#rv-swiper-div').width()) - 10;
> ```

Typo with height
___
*[swiper/src/index.ts, line 97 at r1](https://reviewable.io/reviews/fgpv-vpgf/contributed-plugins/191#-MZTI_3O6ByiMa3jmL72:-MZTI_3O6ByiMa3jmL73:b7zf2ir) ([raw file](https://github.com/fgpv-vpgf/contributed-plugins/blob/764039fb8f716463e647fa62d6c3af234d9c995f/swiper/src/index.ts#L97)):*
> ```XML
>                 }
>                 swipeWidget.swipe();
>                 
> ```

Trailing white spaces
___
*[swiper/src/main.scss, line 83 at r1](https://reviewable.io/reviews/fgpv-vpgf/contributed-plugins/191#-MZTIdXK9BAaXC_u3lzc:-MZTIdXK9BAaXC_u3lzd:bdolal6) ([raw file](https://github.com/fgpv-vpgf/contributed-plugins/blob/764039fb8f716463e647fa62d6c3af234d9c995f/swiper/src/main.scss#L83)):*
> ```SCSS
>         top:50%;
>         content: "";
> 	    height: 1px;
> ```

Replace tab by spaces
___
*[swiper/src/main.scss, line 84 at r1](https://reviewable.io/reviews/fgpv-vpgf/contributed-plugins/191#-MZTIfqk2TA67wJ9nkro:-MZTIfqk2TA67wJ9nkrp:bdolal6) ([raw file](https://github.com/fgpv-vpgf/contributed-plugins/blob/764039fb8f716463e647fa62d6c3af234d9c995f/swiper/src/main.scss#L84)):*
> ```SCSS
>         content: "";
> 	    height: 1px;
> 	    width: 100%;
> ```

Replace tab by spaces
___
*[swiper/src/main.scss, line 93 at r1](https://reviewable.io/reviews/fgpv-vpgf/contributed-plugins/191#-MZTIgXiCn8O6Z5JGZm9:-MZTIgXiCn8O6Z5JGZmA:bdolal6) ([raw file](https://github.com/fgpv-vpgf/contributed-plugins/blob/764039fb8f716463e647fa62d6c3af234d9c995f/swiper/src/main.scss#L93)):*
> ```SCSS
>         top:50%;
>         width: 100%;
>     	height: 11px;
> ```

Replace tab by spaces
___
*[swiper/src/main.scss, line 94 at r1](https://reviewable.io/reviews/fgpv-vpgf/contributed-plugins/191#-MZTIh4p9wGbet38v5C-:-MZTIh4p9wGbet38v5C0:bdolal6) ([raw file](https://github.com/fgpv-vpgf/contributed-plugins/blob/764039fb8f716463e647fa62d6c3af234d9c995f/swiper/src/main.scss#L94)):*
> ```SCSS
>         width: 100%;
>     	height: 11px;
> 	    cursor: row-resize;
> ```

Replace tab by spaces
___
*[swiper/src/main.scss, line 103 at r1](https://reviewable.io/reviews/fgpv-vpgf/contributed-plugins/191#-MZTIhkICKPLsr7yY5mY:-MZTIhkICKPLsr7yY5mZ:bdolal6) ([raw file](https://github.com/fgpv-vpgf/contributed-plugins/blob/764039fb8f716463e647fa62d6c3af234d9c995f/swiper/src/main.scss#L103)):*
> ```SCSS
> 
>         .handle:before {
>   	        height: 1200px;
> ```

Replace tab by spaces
___
*[swiper/src/main.scss, line 104 at r1](https://reviewable.io/reviews/fgpv-vpgf/contributed-plugins/191#-MZTIiFi8_-OwWbKxSI7:-MZTIiFi8_-OwWbKxSI8:bdolal6) ([raw file](https://github.com/fgpv-vpgf/contributed-plugins/blob/764039fb8f716463e647fa62d6c3af234d9c995f/swiper/src/main.scss#L104)):*
> ```SCSS
>         .handle:before {
>   	        height: 1200px;
> 	        width: 100%
> ```

Replace tab by spaces
___
*[swiper/src/main.scss, line 107 at r1](https://reviewable.io/reviews/fgpv-vpgf/contributed-plugins/191#-MZTIj9x736q5MU7-Oe8:-MZTIj9x736q5MU7-Oe9:b7zf2ir) ([raw file](https://github.com/fgpv-vpgf/contributed-plugins/blob/764039fb8f716463e647fa62d6c3af234d9c995f/swiper/src/main.scss#L107)):*
> ```SCSS
>        }
>          .handle:before, .handle:after {
>             content: "\268C";  
> ```

Trailing white spaces
___
*[swiper/src/main.scss, line 122 at r1](https://reviewable.io/reviews/fgpv-vpgf/contributed-plugins/191#-MZTIlbr42twj4p2-39i:-MZTIlbr42twj4p2-39j:bdolal6) ([raw file](https://github.com/fgpv-vpgf/contributed-plugins/blob/764039fb8f716463e647fa62d6c3af234d9c995f/swiper/src/main.scss#L122)):*
> ```SCSS
>             width: 24px;
>             height: 50%;
> 	        margin-top: -20px;
> ```

Replace tab by spaces
___
*[swiper/src/main.scss, line 123 at r1](https://reviewable.io/reviews/fgpv-vpgf/contributed-plugins/191#-MZTImPc-JMIHtvOlvC5:-MZTImPc-JMIHtvOlvC6:bdolal6) ([raw file](https://github.com/fgpv-vpgf/contributed-plugins/blob/764039fb8f716463e647fa62d6c3af234d9c995f/swiper/src/main.scss#L123)):*
> ```SCSS
>             height: 50%;
> 	        margin-top: -20px;
> 	        margin-left: -12px;
> ```

Replace tab by spaces
___
*[swiper/src/main.scss, line 132 at r1](https://reviewable.io/reviews/fgpv-vpgf/contributed-plugins/191#-MZTImug6veBfA6cIYMe:-MZTImug6veBfA6cIYMf:b7zf2ir) ([raw file](https://github.com/fgpv-vpgf/contributed-plugins/blob/764039fb8f716463e647fa62d6c3af234d9c995f/swiper/src/main.scss#L132)):*
> ```SCSS
>             top: 50%;
>         }
>     }   
> ```

Trailing white spaces
___
*[swiper/src/main.scss, line 137 at r1](https://reviewable.io/reviews/fgpv-vpgf/contributed-plugins/191#-MZTIpwQ3F8Ip2fzooX2:-MZTIpwQ3F8Ip2fzooX3:b7zf2ir) ([raw file](https://github.com/fgpv-vpgf/contributed-plugins/blob/764039fb8f716463e647fa62d6c3af234d9c995f/swiper/src/main.scss#L137)):*
> ```SCSS
>         filter: progid:DXImageTransform.Microsoft.Alpha(Opacity=75);
>         opacity: 0.75;
>     }    
> ```

Trailing white spaces

**Review by Pewillia — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/fgpv-vpgf/contributed-plugins/191)* status: 2 of 4 files reviewed, 15 unresolved discussions (waiting on @jolevesq)

___
*[swiper/src/index.ts, line 67 at r1](https://reviewable.io/reviews/fgpv-vpgf/contributed-plugins/191#-MZTCPuk25e7QsRjzUkV:-MZTgmBjA01E-aPYbV7z:b-896fix) ([raw file](https://github.com/fgpv-vpgf/contributed-plugins/blob/764039fb8f716463e647fa62d6c3af234d9c995f/swiper/src/index.ts#L67)):*
<details><summary><i>Previously, jolevesq (Johann Levesque) wrote…</i></summary><blockquote>

Use string literal `#rv-swiper-div .${swipeWidget.type}`
</blockquote></details>

Done.
___
*[swiper/src/index.ts, line 74 at r1](https://reviewable.io/reviews/fgpv-vpgf/contributed-plugins/191#-MZTHxcX00ktcrtOGdY9:-MZThVbU5ux_LXVdsMsa:b-896fix) ([raw file](https://github.com/fgpv-vpgf/contributed-plugins/blob/764039fb8f716463e647fa62d6c3af234d9c995f/swiper/src/index.ts#L74)):*
<details><summary><i>Previously, jolevesq (Johann Levesque) wrote…</i></summary><blockquote>

Trailing white spaces
</blockquote></details>

Done.
___
*[swiper/src/index.ts, line 86 at r1](https://reviewable.io/reviews/fgpv-vpgf/contributed-plugins/191#-MZTI2mg8yhA52sFM-rF:-MZTiS9G3x2Wl6Aa89Fb:b-896fix) ([raw file](https://github.com/fgpv-vpgf/contributed-plugins/blob/764039fb8f716463e647fa62d6c3af234d9c995f/swiper/src/index.ts#L86)):*
<details><summary><i>Previously, jolevesq (Johann Levesque) wrote…</i></summary><blockquote>

Typo with height
</blockquote></details>

Done.
___
*[swiper/src/index.ts, line 97 at r1](https://reviewable.io/reviews/fgpv-vpgf/contributed-plugins/191#-MZTI_3O6ByiMa3jmL72:-MZTiago-rar5mojJQ18:b-896fix) ([raw file](https://github.com/fgpv-vpgf/contributed-plugins/blob/764039fb8f716463e647fa62d6c3af234d9c995f/swiper/src/index.ts#L97)):*
<details><summary><i>Previously, jolevesq (Johann Levesque) wrote…</i></summary><blockquote>

Trailing white spaces
</blockquote></details>

Done.
___
*[swiper/src/main.scss, line 83 at r1](https://reviewable.io/reviews/fgpv-vpgf/contributed-plugins/191#-MZTIdXK9BAaXC_u3lzc:-MZTjtUn73dBZRQq7edL:b-896fix) ([raw file](https://github.com/fgpv-vpgf/contributed-plugins/blob/764039fb8f716463e647fa62d6c3af234d9c995f/swiper/src/main.scss#L83)):*
<details><summary><i>Previously, jolevesq (Johann Levesque) wrote…</i></summary><blockquote>

Replace tab by spaces
</blockquote></details>

Done.
___
*[swiper/src/main.scss, line 84 at r1](https://reviewable.io/reviews/fgpv-vpgf/contributed-plugins/191#-MZTIfqk2TA67wJ9nkro:-MZTjx0mDO0WeXg3DdOt:b-896fix) ([raw file](https://github.com/fgpv-vpgf/contributed-plugins/blob/764039fb8f716463e647fa62d6c3af234d9c995f/swiper/src/main.scss#L84)):*
<details><summary><i>Previously, jolevesq (Johann Levesque) wrote…</i></summary><blockquote>

Replace tab by spaces
</blockquote></details>

Done.
___
*[swiper/src/main.scss, line 93 at r1](https://reviewable.io/reviews/fgpv-vpgf/contributed-plugins/191#-MZTIgXiCn8O6Z5JGZm9:-MZTk0bYDKiAewdiQNG3:b-896fix) ([raw file](https://github.com/fgpv-vpgf/contributed-plugins/blob/764039fb8f716463e647fa62d6c3af234d9c995f/swiper/src/main.scss#L93)):*
<details><summary><i>Previously, jolevesq (Johann Levesque) wrote…</i></summary><blockquote>

Replace tab by spaces
</blockquote></details>

Done.
___
*[swiper/src/main.scss, line 94 at r1](https://reviewable.io/reviews/fgpv-vpgf/contributed-plugins/191#-MZTIh4p9wGbet38v5C-:-MZTk3SnDx6KxREM2H-n:b-896fix) ([raw file](https://github.com/fgpv-vpgf/contributed-plugins/blob/764039fb8f716463e647fa62d6c3af234d9c995f/swiper/src/main.scss#L94)):*
<details><summary><i>Previously, jolevesq (Johann Levesque) wrote…</i></summary><blockquote>

Replace tab by spaces
</blockquote></details>

Done.
___
*[swiper/src/main.scss, line 103 at r1](https://reviewable.io/reviews/fgpv-vpgf/contributed-plugins/191#-MZTIhkICKPLsr7yY5mY:-MZTkB-L8LSOxgadFzR2:b-896fix) ([raw file](https://github.com/fgpv-vpgf/contributed-plugins/blob/764039fb8f716463e647fa62d6c3af234d9c995f/swiper/src/main.scss#L103)):*
<details><summary><i>Previously, jolevesq (Johann Levesque) wrote…</i></summary><blockquote>

Replace tab by spaces
</blockquote></details>

Done.
___
*[swiper/src/main.scss, line 104 at r1](https://reviewable.io/reviews/fgpv-vpgf/contributed-plugins/191#-MZTIiFi8_-OwWbKxSI7:-MZTkBNo6rRMOhpR2WHw:b-896fix) ([raw file](https://github.com/fgpv-vpgf/contributed-plugins/blob/764039fb8f716463e647fa62d6c3af234d9c995f/swiper/src/main.scss#L104)):*
<details><summary><i>Previously, jolevesq (Johann Levesque) wrote…</i></summary><blockquote>

Replace tab by spaces
</blockquote></details>

Done.
___
*[swiper/src/main.scss, line 107 at r1](https://reviewable.io/reviews/fgpv-vpgf/contributed-plugins/191#-MZTIj9x736q5MU7-Oe8:-MZTkH9U3guPS7H1jLJF:b-896fix) ([raw file](https://github.com/fgpv-vpgf/contributed-plugins/blob/764039fb8f716463e647fa62d6c3af234d9c995f/swiper/src/main.scss#L107)):*
<details><summary><i>Previously, jolevesq (Johann Levesque) wrote…</i></summary><blockquote>

Trailing white spaces
</blockquote></details>

Done.
___
*[swiper/src/main.scss, line 122 at r1](https://reviewable.io/reviews/fgpv-vpgf/contributed-plugins/191#-MZTIlbr42twj4p2-39i:-MZTkMCj-hFKccu4n_7w:b-896fix) ([raw file](https://github.com/fgpv-vpgf/contributed-plugins/blob/764039fb8f716463e647fa62d6c3af234d9c995f/swiper/src/main.scss#L122)):*
<details><summary><i>Previously, jolevesq (Johann Levesque) wrote…</i></summary><blockquote>

Replace tab by spaces
</blockquote></details>

Done.
___
*[swiper/src/main.scss, line 123 at r1](https://reviewable.io/reviews/fgpv-vpgf/contributed-plugins/191#-MZTImPc-JMIHtvOlvC5:-MZTkPUL24ULqtW71JA6:b-896fix) ([raw file](https://github.com/fgpv-vpgf/contributed-plugins/blob/764039fb8f716463e647fa62d6c3af234d9c995f/swiper/src/main.scss#L123)):*
<details><summary><i>Previously, jolevesq (Johann Levesque) wrote…</i></summary><blockquote>

Replace tab by spaces
</blockquote></details>

Done.
___
*[swiper/src/main.scss, line 132 at r1](https://reviewable.io/reviews/fgpv-vpgf/contributed-plugins/191#-MZTImug6veBfA6cIYMe:-MZTkT-E62mz3ZoYj0lL:b-896fix) ([raw file](https://github.com/fgpv-vpgf/contributed-plugins/blob/764039fb8f716463e647fa62d6c3af234d9c995f/swiper/src/main.scss#L132)):*
<details><summary><i>Previously, jolevesq (Johann Levesque) wrote…</i></summary><blockquote>

Trailing white spaces
</blockquote></details>

Done.
___
*[swiper/src/main.scss, line 137 at r1](https://reviewable.io/reviews/fgpv-vpgf/contributed-plugins/191#-MZTIpwQ3F8Ip2fzooX2:-MZTkWOT5XaXF0fosxmU:b-896fix) ([raw file](https://github.com/fgpv-vpgf/contributed-plugins/blob/764039fb8f716463e647fa62d6c3af234d9c995f/swiper/src/main.scss#L137)):*
<details><summary><i>Previously, jolevesq (Johann Levesque) wrote…</i></summary><blockquote>

Trailing white spaces
</blockquote></details>

Done.

**Review by jolevesq — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/fgpv-vpgf/contributed-plugins/191)* status: 2 of 4 files reviewed, 3 unresolved discussions (waiting on @jolevesq)

___
*[swiper/src/main.scss, line 107 at r1](https://reviewable.io/reviews/fgpv-vpgf/contributed-plugins/191#-MZTIj9x736q5MU7-Oe8:-MZXYIMBEkTfoZpPpiOb:b-8dahjt) ([raw file](https://github.com/fgpv-vpgf/contributed-plugins/blob/764039fb8f716463e647fa62d6c3af234d9c995f/swiper/src/main.scss#L107)):*
<details><summary><i>Previously, jolevesq (Johann Levesque) wrote…</i></summary><blockquote>

Trailing white spaces
</blockquote></details>

Still there
___
*[swiper/src/main.scss, line 132 at r1](https://reviewable.io/reviews/fgpv-vpgf/contributed-plugins/191#-MZTImug6veBfA6cIYMe:-MZXYKe4CV8feEAePJMW:b-8dahjt) ([raw file](https://github.com/fgpv-vpgf/contributed-plugins/blob/764039fb8f716463e647fa62d6c3af234d9c995f/swiper/src/main.scss#L132)):*
<details><summary><i>Previously, jolevesq (Johann Levesque) wrote…</i></summary><blockquote>

Trailing white spaces
</blockquote></details>

Still there
___
*[swiper/src/main.scss, line 137 at r1](https://reviewable.io/reviews/fgpv-vpgf/contributed-plugins/191#-MZTIpwQ3F8Ip2fzooX2:-MZXYLxm6cyAzLJapt86:bz2tcqv) ([raw file](https://github.com/fgpv-vpgf/contributed-plugins/blob/764039fb8f716463e647fa62d6c3af234d9c995f/swiper/src/main.scss#L137)):*
<details><summary><i>Previously, jolevesq (Johann Levesque) wrote…</i></summary><blockquote>

Trailing white spaces
</blockquote></details>

still there

**Review by Pewillia — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/fgpv-vpgf/contributed-plugins/191)* status: 2 of 4 files reviewed, 3 unresolved discussions (waiting on @jolevesq)

___
*[swiper/src/main.scss, line 107 at r1](https://reviewable.io/reviews/fgpv-vpgf/contributed-plugins/191#-MZTIj9x736q5MU7-Oe8:-MZrawXR5lcjHj0YfsI-:b-896fix) ([raw file](https://github.com/fgpv-vpgf/contributed-plugins/blob/764039fb8f716463e647fa62d6c3af234d9c995f/swiper/src/main.scss#L107)):*
<details><summary><i>Previously, jolevesq (Johann Levesque) wrote…</i></summary><blockquote>

Still there
</blockquote></details>

Done.
___
*[swiper/src/main.scss, line 132 at r1](https://reviewable.io/reviews/fgpv-vpgf/contributed-plugins/191#-MZTImug6veBfA6cIYMe:-MZrZyWx1prBdUZqsb5b:b-896fix) ([raw file](https://github.com/fgpv-vpgf/contributed-plugins/blob/764039fb8f716463e647fa62d6c3af234d9c995f/swiper/src/main.scss#L132)):*
<details><summary><i>Previously, jolevesq (Johann Levesque) wrote…</i></summary><blockquote>

Still there
</blockquote></details>

Done.
___
*[swiper/src/main.scss, line 137 at r1](https://reviewable.io/reviews/fgpv-vpgf/contributed-plugins/191#-MZTIpwQ3F8Ip2fzooX2:-MZr_AIm4pehrBKjlOaW:b-896fix) ([raw file](https://github.com/fgpv-vpgf/contributed-plugins/blob/764039fb8f716463e647fa62d6c3af234d9c995f/swiper/src/main.scss#L137)):*
<details><summary><i>Previously, jolevesq (Johann Levesque) wrote…</i></summary><blockquote>

still there
</blockquote></details>

Done.

**Review by jolevesq — APPROVED** [review]
:lgtm:

> Reviewed 2 of 2 files at r2.
> *[Reviewable](https://reviewable.io/reviews/fgpv-vpgf/contributed-plugins/191#-:-MZrdIr42n8Nw7c2olPo:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @Pewillia)

**Pull request merged**
