### PR TITLE
fix(range): Fix ui for mobile and laptop plus fix a problem with date…

### LINKED ISSUE #93: Add minimize/maximize view options to Range Slider interface
As a user, I would like an option to minimize/maximize the range slider interface. A minimized display of action buttons for a better view of the map, especially for viewing on smaller platforms, would benefit UX.

Example: It could also include the loop and reset buttons if available in the maximized view of the interface

2020-09-30_12_07_10-Plugin_ Range Slider

### PR DESCRIPTION
**Pull request by jolevesq**
… slider and dynamic limit

Closes #93

---
This change is [Reviewable](https://reviewable.io/reviews/fgpv-vpgf/contributed-plugins/105)

### CODE REVIEW

**Comment by aparujan** [comment]
___
*[range-slider/src/main.scss, line 30 at r1](https://reviewable.io/reviews/fgpv-vpgf/contributed-plugins/105#-MKq2a9B9fyKW7k08CWT:-MKq2a9C6wFpet5dLo1C:b-skvf9s) ([raw file](https://github.com/fgpv-vpgf/contributed-plugins/blob/d250d3d3cee18e4e66d7eee23cf3a3dffd063e30/range-slider/src/main.scss#L30)):*
> ```SCSS
>                     .slider-bar {
>                         @include small-padding;
>     
> ```

Extra spaces, but I think these were intentional?

**Comment by aparujan** [comment]
___
*[range-slider/src/main.scss, line 34 at r1](https://reviewable.io/reviews/fgpv-vpgf/contributed-plugins/105#-MKq2gBN7aeaZOZFyH_H:-MKq2gBN7aeaZOZFyH_I:b-skvf9s) ([raw file](https://github.com/fgpv-vpgf/contributed-plugins/blob/d250d3d3cee18e4e66d7eee23cf3a3dffd063e30/range-slider/src/main.scss#L34)):*
> ```SCSS
>                             display: none !important;
>                         }
>     
> ```

Extra spaces, but I think these were intentional?

**Comment by aparujan** [comment]
___
*[range-slider/src/main.scss, line 102 at r1](https://reviewable.io/reviews/fgpv-vpgf/contributed-plugins/105#-MKq2sVx7QbgqQAalGZp:-MKq2sVx7QbgqQAalGZq:b-lqyvqd) ([raw file](https://github.com/fgpv-vpgf/contributed-plugins/blob/d250d3d3cee18e4e66d7eee23cf3a3dffd063e30/range-slider/src/main.scss#L102)):*
> ```SCSS
> }
> 
> // smaller then laptop large and larger then a tablet
> ```

sentence wording. ..

Perhaps, "Small than a laptop, larger than a tablet"

**Review by aparujan — COMMENTED** [review]
> Reviewed 6 of 6 files at r1.
> *[Reviewable](https://reviewable.io/reviews/fgpv-vpgf/contributed-plugins/105)* status: all files reviewed, 3 unresolved discussions (waiting on @jolevesq)

**Review by jolevesq — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/fgpv-vpgf/contributed-plugins/105)* status: 5 of 6 files reviewed, 3 unresolved discussions (waiting on @aparujan)

___
*[range-slider/src/main.scss, line 30 at r1](https://reviewable.io/reviews/fgpv-vpgf/contributed-plugins/105#-MKq2a9B9fyKW7k08CWT:-MKtN4_d-yReXq3rZZSL:b-896fix) ([raw file](https://github.com/fgpv-vpgf/contributed-plugins/blob/d250d3d3cee18e4e66d7eee23cf3a3dffd063e30/range-slider/src/main.scss#L30)):*
<details><summary><i>Previously, aparujan (Akhil Parujanwala) wrote…</i></summary><blockquote>

Extra spaces, but I think these were intentional?
</blockquote></details>

Done.
___
*[range-slider/src/main.scss, line 34 at r1](https://reviewable.io/reviews/fgpv-vpgf/contributed-plugins/105#-MKq2gBN7aeaZOZFyH_H:-MKtN87lCqTsN6f7JSLn:b-896fix) ([raw file](https://github.com/fgpv-vpgf/contributed-plugins/blob/d250d3d3cee18e4e66d7eee23cf3a3dffd063e30/range-slider/src/main.scss#L34)):*
<details><summary><i>Previously, aparujan (Akhil Parujanwala) wrote…</i></summary><blockquote>

Extra spaces, but I think these were intentional?
</blockquote></details>

Done.
___
*[range-slider/src/main.scss, line 102 at r1](https://reviewable.io/reviews/fgpv-vpgf/contributed-plugins/105#-MKq2sVx7QbgqQAalGZp:-MKtNK5a9JoMyjWwpXOl:b-896fix) ([raw file](https://github.com/fgpv-vpgf/contributed-plugins/blob/d250d3d3cee18e4e66d7eee23cf3a3dffd063e30/range-slider/src/main.scss#L102)):*
<details><summary><i>Previously, aparujan (Akhil Parujanwala) wrote…</i></summary><blockquote>

sentence wording. ..

Perhaps, "Small than a laptop, larger than a tablet"
</blockquote></details>

Done.

**Comment by aparujan** [comment]
___
*[range-slider/src/main.scss, line 102 at r1](https://reviewable.io/reviews/fgpv-vpgf/contributed-plugins/105#-MKq2sVx7QbgqQAalGZp:-MKtOZ1O5KCd15bnhlzW:bds1hs9) ([raw file](https://github.com/fgpv-vpgf/contributed-plugins/blob/d250d3d3cee18e4e66d7eee23cf3a3dffd063e30/range-slider/src/main.scss#L102)):*
<details><summary><i>Previously, jolevesq (Johann Levesque) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

One more thing I jsut realized,

"Smaller" as opposed to "Small"

**Review by aparujan — COMMENTED** [review]
> Reviewed 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/fgpv-vpgf/contributed-plugins/105)* status: all files reviewed, 1 unresolved discussion (waiting on @jolevesq)

**Review by aparujan — APPROVED** [review]
> Reviewed 1 of 1 files at r3.
> *[Reviewable](https://reviewable.io/reviews/fgpv-vpgf/contributed-plugins/105)* status: :shipit: complete! all files reviewed, all discussions resolved

**Pull request merged**
