### PR TITLE
323 add markdown layer desc

### PR DESCRIPTION
**Pull request by Pewillia**
This change is [Reviewable](https://reviewable.io/reviews/fgpv-vpgf/contributed-plugins/332)

### CODE REVIEW

**Review by jolevesq — CHANGES_REQUESTED** [review]
> Reviewed 3 of 7 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/fgpv-vpgf/contributed-plugins/332)* status: 3 of 7 files reviewed, 5 unresolved discussions (waiting on @jolevesq and @Pewillia)

___
*[thematic-slider/package.json, line 42 at r1](https://reviewable.io/reviews/fgpv-vpgf/contributed-plugins/332#-Mnek7WKEH3AMMPyRbjI:-Mnek7WKEH3AMMPyRbjJ:b-89zy1b) ([raw file](https://github.com/fgpv-vpgf/contributed-plugins/blob/936316c8c2f46f27f8f9eeebe6f7734789ecb105/thematic-slider/package.json#L42)):*
> ```JSON
>         "fibers": "5.0.0",
>         "file-loader": "6.2.0",
>         "markdown-it": "12.2.0",
> ```

For markdown library, please the same as chart: "showdown": "1.9.1". We will minimize the number of library we need to follow.
___
*[thematic-slider/src/main.scss, line 32 at r1](https://reviewable.io/reviews/fgpv-vpgf/contributed-plugins/332#-MnekKbpAe7PXDtyo0pN:-MnekKbpAe7PXDtyo0pO:b-vfmp8a) ([raw file](https://github.com/fgpv-vpgf/contributed-plugins/blob/936316c8c2f46f27f8f9eeebe6f7734789ecb105/thematic-slider/src/main.scss#L32)):*
> ```SCSS
>     right: 10px;
> }
> ```

There is 2 blank line, remove one of them
___
*[thematic-slider/src/main.scss, line 37 at r1](https://reviewable.io/reviews/fgpv-vpgf/contributed-plugins/332#-MnekQCQBptcqHXvLOuS:-MnekQCQBptcqHXvLOuT:b-197rmb) ([raw file](https://github.com/fgpv-vpgf/contributed-plugins/blob/936316c8c2f46f27f8f9eeebe6f7734789ecb105/thematic-slider/src/main.scss#L37)):*
> ```SCSS
>     overflow-wrap: break-word;
>     word-wrap: break-word;
>     white-space : pre-wrap !important;
> ```

No space before :
___
*[thematic-slider/src/main.scss, line 38 at r1](https://reviewable.io/reviews/fgpv-vpgf/contributed-plugins/332#-MnekS4VDB7Th68slrpG:-MnekS4VDB7Th68slrpH:b-3j25kd) ([raw file](https://github.com/fgpv-vpgf/contributed-plugins/blob/936316c8c2f46f27f8f9eeebe6f7734789ecb105/thematic-slider/src/main.scss#L38)):*
> ```SCSS
>     word-wrap: break-word;
>     white-space : pre-wrap !important;
>    img {
> ```

Indentation is wrong
___
*[thematic-slider/src/samples/thematic-slider-index.html, line 40 at r1](https://reviewable.io/reviews/fgpv-vpgf/contributed-plugins/332#-MnekbGm2tt_dU58SMuZ:-MnekbGm2tt_dU58SMu_:bskfw69) ([raw file](https://github.com/fgpv-vpgf/contributed-plugins/blob/936316c8c2f46f27f8f9eeebe6f7734789ecb105/thematic-slider/src/samples/thematic-slider-index.html#L40)):*
> ```HTML
>                     <option value="thematic-slider-unused-layer.json">11. Unused Layer, autorun with controls</option>
>                     <option value="thematic-slider-test-file-extent.json">12. Extent with Layer, Open by default</option>
> 					<option value="thematic-slider-markup.json">13. Markup test</option>
> ```

There is tabbing character instead of spaces

**Review by Pewillia — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/fgpv-vpgf/contributed-plugins/332)* status: 3 of 7 files reviewed, 5 unresolved discussions (waiting on @jolevesq)

___
*[thematic-slider/package.json, line 42 at r1](https://reviewable.io/reviews/fgpv-vpgf/contributed-plugins/332#-Mnek7WKEH3AMMPyRbjI:-MnfDdA4-ImrVcWv1SPo:b-896fix) ([raw file](https://github.com/fgpv-vpgf/contributed-plugins/blob/936316c8c2f46f27f8f9eeebe6f7734789ecb105/thematic-slider/package.json#L42)):*
<details><summary><i>Previously, jolevesq (Johann Levesque) wrote…</i></summary><blockquote>

For markdown library, please the same as chart: "showdown": "1.9.1". We will minimize the number of library we need to follow.
</blockquote></details>

Done.
___
*[thematic-slider/src/main.scss, line 32 at r1](https://reviewable.io/reviews/fgpv-vpgf/contributed-plugins/332#-MnekKbpAe7PXDtyo0pN:-MnfDl3b6-8Imvhxdxzs:b-896fix) ([raw file](https://github.com/fgpv-vpgf/contributed-plugins/blob/936316c8c2f46f27f8f9eeebe6f7734789ecb105/thematic-slider/src/main.scss#L32)):*
<details><summary><i>Previously, jolevesq (Johann Levesque) wrote…</i></summary><blockquote>

There is 2 blank line, remove one of them
</blockquote></details>

Done.
___
*[thematic-slider/src/main.scss, line 37 at r1](https://reviewable.io/reviews/fgpv-vpgf/contributed-plugins/332#-MnekQCQBptcqHXvLOuS:-MnfDm024UiNrxaJjYvm:b-896fix) ([raw file](https://github.com/fgpv-vpgf/contributed-plugins/blob/936316c8c2f46f27f8f9eeebe6f7734789ecb105/thematic-slider/src/main.scss#L37)):*
<details><summary><i>Previously, jolevesq (Johann Levesque) wrote…</i></summary><blockquote>

No space before :
</blockquote></details>

Done.
___
*[thematic-slider/src/main.scss, line 38 at r1](https://reviewable.io/reviews/fgpv-vpgf/contributed-plugins/332#-MnekS4VDB7Th68slrpG:-MnfDmcu2dKJ4X5jtXN5:b-896fix) ([raw file](https://github.com/fgpv-vpgf/contributed-plugins/blob/936316c8c2f46f27f8f9eeebe6f7734789ecb105/thematic-slider/src/main.scss#L38)):*
<details><summary><i>Previously, jolevesq (Johann Levesque) wrote…</i></summary><blockquote>

Indentation is wrong
</blockquote></details>

Done.
___
*[thematic-slider/src/samples/thematic-slider-index.html, line 40 at r1](https://reviewable.io/reviews/fgpv-vpgf/contributed-plugins/332#-MnekbGm2tt_dU58SMuZ:-MnfDoLQASM9pxBB1a73:b-896fix) ([raw file](https://github.com/fgpv-vpgf/contributed-plugins/blob/936316c8c2f46f27f8f9eeebe6f7734789ecb105/thematic-slider/src/samples/thematic-slider-index.html#L40)):*
<details><summary><i>Previously, jolevesq (Johann Levesque) wrote…</i></summary><blockquote>

There is tabbing character instead of spaces
</blockquote></details>

Done.

**Review by jolevesq — CHANGES_REQUESTED** [review]
> Reviewed 1 of 4 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/fgpv-vpgf/contributed-plugins/332)* status: 4 of 7 files reviewed, 2 unresolved discussions (waiting on @jolevesq and @Pewillia)

___
*[thematic-slider/src/main.scss, line 38 at r1](https://reviewable.io/reviews/fgpv-vpgf/contributed-plugins/332#-MnekS4VDB7Th68slrpG:-MnlEA-y8X_yIIklgOJs:b-8l5xx) ([raw file](https://github.com/fgpv-vpgf/contributed-plugins/blob/936316c8c2f46f27f8f9eeebe6f7734789ecb105/thematic-slider/src/main.scss#L38)):*
<details><summary><i>Previously, Pewillia wrote…</i></summary><blockquote>

Done.
</blockquote></details>

My bad, haven't seen it first time, need a space after :
___
*[thematic-slider/src/slider-panel.ts, line 172 at r2](https://reviewable.io/reviews/fgpv-vpgf/contributed-plugins/332#-MnlEHAaAU41BwqbTbrr:-MnlEHAaAU41BwqbTbrs:byen087) ([raw file](https://github.com/fgpv-vpgf/contributed-plugins/blob/b67a615a3aa79fe8272e880041873efe5cc8404f/thematic-slider/src/slider-panel.ts#L172)):*
> ```XML
>     private setPanelInfo() {
>         let converter = new showdown.Converter();
>  
> ```

Trailing white spaces

**Review by Pewillia — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/fgpv-vpgf/contributed-plugins/332)* status: 4 of 7 files reviewed, 2 unresolved discussions (waiting on @jolevesq)

___
*[thematic-slider/src/main.scss, line 38 at r1](https://reviewable.io/reviews/fgpv-vpgf/contributed-plugins/332#-MnekS4VDB7Th68slrpG:-MnlZjydD5uFl5Hn6-1N:b-896fix) ([raw file](https://github.com/fgpv-vpgf/contributed-plugins/blob/936316c8c2f46f27f8f9eeebe6f7734789ecb105/thematic-slider/src/main.scss#L38)):*
<details><summary><i>Previously, jolevesq (Johann Levesque) wrote…</i></summary><blockquote>

My bad, haven't seen it first time, need a space after :
</blockquote></details>

Done.
___
*[thematic-slider/src/slider-panel.ts, line 172 at r2](https://reviewable.io/reviews/fgpv-vpgf/contributed-plugins/332#-MnlEHAaAU41BwqbTbrr:-Mnl_1ywEsGY4MXKsFzO:b-896fix) ([raw file](https://github.com/fgpv-vpgf/contributed-plugins/blob/b67a615a3aa79fe8272e880041873efe5cc8404f/thematic-slider/src/slider-panel.ts#L172)):*
<details><summary><i>Previously, jolevesq (Johann Levesque) wrote…</i></summary><blockquote>

Trailing white spaces
</blockquote></details>

Done.

**Review by jolevesq — COMMENTED** [review]
:lgtm: 

> Reviewed 1 of 4 files at r2, 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/fgpv-vpgf/contributed-plugins/332#-:-MnzYtYGC66mZCF7-Xgp:bg7igkv)* status: all files reviewed, 1 unresolved discussion (waiting on @jolevesq)

**Review by jolevesq — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/fgpv-vpgf/contributed-plugins/332)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @Pewillia)

**Pull request merged**
