### PR TITLE
feat(Range): Support esriImage layer and hours extent for WMS-T plus …

### LINKED ISSUE #65: Autoplay and loop for Range slider
Add the autoplay and loop like what we have for thematic slider

### PR DESCRIPTION
**Pull request by jolevesq**
…update the loop and autorun. At the same time add single range type and static limit.

Closes #65, #75, #86

---
This change is [Reviewable](https://reviewable.io/reviews/fgpv-vpgf/contributed-plugins/92)

### CODE REVIEW

**Comment by aparujan** [comment]
___
*[range-slider/README.md, line 50 at r1](https://reviewable.io/reviews/fgpv-vpgf/contributed-plugins/92#-MIU2Kol3gXL7JbTogGy:-MIU2Kom9r6iuQ0ZyBDJ:b57i26h) ([raw file](https://github.com/fgpv-vpgf/contributed-plugins/blob/97b448af0bd25f8a32f7ee2636c99c3f1439f503/range-slider/README.md#L50)):*
> ```Markdown
>     - rangeType: The type of range (single for one handle or dual for 2 handles (range))
>     - stepType: The type of step (dynamic for open values or static from a list of values)
>     - precision: The precision of numeric data or 'date' - 'hour' for date data 
> ```

extra space after "data"

**Comment by aparujan** [comment]
___
*[range-slider/README.md, line 67 at r1](https://reviewable.io/reviews/fgpv-vpgf/contributed-plugins/92#-MIU2kndD_5iwLqNDBS6:-MIU2kndD_5iwLqNDBS7:b-vin55k) ([raw file](https://github.com/fgpv-vpgf/contributed-plugins/blob/97b448af0bd25f8a32f7ee2636c99c3f1439f503/range-slider/README.md#L67)):*
> ```Markdown
> NOTE: You can't have a rangeType 'single' with a stepType 'dynamic.
> 
> NOTE: To have the slider initialize the values from the layers, layer must be ESRI type with dual range type and dynamic limit. Whit the other type of range and limit, it is better to define the limit with multiple that can
> ```

Possibly typo, "Whit", I belive it could be "With"?

**Comment by aparujan** [comment]
___
*[range-slider/src/slider-bar.ts, line 111 at r1](https://reviewable.io/reviews/fgpv-vpgf/contributed-plugins/92#-MIU433N94VAtAn9fSaB:-MIU433O63eLorP19nBk:b-d8iscj) ([raw file](https://github.com/fgpv-vpgf/contributed-plugins/blob/97b448af0bd25f8a32f7ee2636c99c3f1439f503/range-slider/src/slider-bar.ts#L111)):*
> ```XML
>             let ox = Math.abs(d1.x - d2.x) < (d1.x < d2.x ? d2.width : d1.width);
>             let oy = Math.abs(d1.y - d2.y) < (d1.y < d2.y ? d2.height : d1.height);
>             
> ```

Perhaps use a carriage return or leave the space as it such that the loop is easier to read.

**Comment by aparujan** [comment]
___
*[range-slider/src/slider-bar.ts, line 225 at r1](https://reviewable.io/reviews/fgpv-vpgf/contributed-plugins/92#-MIU4T-cCF-I4rayUut7:-MIU4T-cCF-I4rayUut8:b-l9n9kf) ([raw file](https://github.com/fgpv-vpgf/contributed-plugins/blob/97b448af0bd25f8a32f7ee2636c99c3f1439f503/range-slider/src/slider-bar.ts#L225)):*
> ```XML
>             }
>         }
>         
> ```

extra space

**Comment by aparujan** [comment]
___
*[range-slider/src/slider-bar.ts, line 234 at r1](https://reviewable.io/reviews/fgpv-vpgf/contributed-plugins/92#-MIU4W8m3BJrBmF-wWz_:-MIU4W8m3BJrBmF-wWza:b-l9n9kf) ([raw file](https://github.com/fgpv-vpgf/contributed-plugins/blob/97b448af0bd25f8a32f7ee2636c99c3f1439f503/range-slider/src/slider-bar.ts#L234)):*
> ```XML
>             tooltips.push({ to: (value: number) => this.formatPips(value, type, language), from: Number })
>         }
>         
> ```

extra space

**Comment by aparujan** [comment]
___
*[range-slider/src/slider-bar.ts, line 390 at r1](https://reviewable.io/reviews/fgpv-vpgf/contributed-plugins/92#-MIU4eGVCaDYJ2jTCG-o:-MIU4eGVCaDYJ2jTCG-p:b-l9n9kf) ([raw file](https://github.com/fgpv-vpgf/contributed-plugins/blob/97b448af0bd25f8a32f7ee2636c99c3f1439f503/range-slider/src/slider-bar.ts#L390)):*
> ```XML
>                 this._slider.range.max = this.limit.staticItems[(this.limit.staticItems.length - 1) - index];
>             }
>             
> ```

extra space

**Comment by aparujan** [comment]
___
*[range-slider/src/slider-bar.ts, line 532 at r1](https://reviewable.io/reviews/fgpv-vpgf/contributed-plugins/92#-MIU4kRu-OKr2_wZhDGY:-MIU4kRu-OKr2_wZhDGZ:b-l9n9kf) ([raw file](https://github.com/fgpv-vpgf/contributed-plugins/blob/97b448af0bd25f8a32f7ee2636c99c3f1439f503/range-slider/src/slider-bar.ts#L532)):*
> ```XML
>                 const stepLeft = (direction === 'up') ? this._slider.noUiSlider.steps()[0][1] : -this._slider.noUiSlider.steps()[0][0];
>                 const stepRight = (direction === 'up') ? this._slider.noUiSlider.steps()[1][1] : -this._slider.noUiSlider.steps()[1][0];
>                 
> ```

extra space

**Comment by aparujan** [comment]
___
*[range-slider/src/slider-manager.ts, line 72 at r1](https://reviewable.io/reviews/fgpv-vpgf/contributed-plugins/92#-MIU6JA39SfAyZKhVV6R:-MIU6JA39SfAyZKhVV6S:b-l9n9kf) ([raw file](https://github.com/fgpv-vpgf/contributed-plugins/blob/97b448af0bd25f8a32f7ee2636c99c3f1439f503/range-slider/src/slider-manager.ts#L72)):*
> ```XML
>                     if (imageIndex >= 0) { sliderImage.push(this._config.translations.bar.esriImageNote)}
>                     if (this._config.description !== '') { sliderImage.unshift(this._config.description); }
>                     
> ```

extra space

**Comment by aparujan** [comment]
___
*[range-slider/src/samples/slider-dual-static-config.json, line 52 at r1](https://reviewable.io/reviews/fgpv-vpgf/contributed-plugins/92#-MIU6uf80kIax2F4m92M:-MIU6uf80kIax2F4m92N:bvlw30w) ([raw file](https://github.com/fgpv-vpgf/contributed-plugins/blob/97b448af0bd25f8a32f7ee2636c99c3f1439f503/range-slider/src/samples/slider-dual-static-config.json#L52)):*
> ```JSON
>         "legend": {},
>         "footnote": {
>           "value": "This is a footnote added from the configuration file. The note is very long so it should wrap on multiple lines when it reaches a certain limit in size. Maybe some user will want to use this as aplace holder to put a lot of information so we need to be able to wrap this content. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Fusce aliquet ante quis aliquet feugiat. Cras eget semper nunc, eu placerat purus. Nunc sed lacinia enim, ut sollicitudin quam. Nunc quis finibus massa, eget maximus enim. Donec ac nisl libero. Nunc eu pharetra arcu. Fusce luctus, magna cursus gravida tristique, risus nisi porttitor magna, ac dictum ipsum dui vel nulla. Integer id ornare augue. Quisque condimentum velit quis elementum porta. Sed dui enim, iaculis cursus diam volutpat, laoreet porta quam. Sed nec aliquet magna. Curabitur commodo fringilla metus, eu posuere sapien mollis nec."
> ```

this as 'a' place holder. * put a space after the 'a' and before 'place'

**Review by aparujan — COMMENTED** [review]
> Reviewed 26 of 26 files at r1.
> *[Reviewable](https://reviewable.io/reviews/fgpv-vpgf/contributed-plugins/92)* status: all files reviewed, 9 unresolved discussions (waiting on @jolevesq)

**Review by aparujan — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/fgpv-vpgf/contributed-plugins/92#-:-MIU9wEG0JrWpESk8w8e:bnfp4nl)* status: all files reviewed, 9 unresolved discussions (waiting on @jolevesq)

**Review by jolevesq — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/fgpv-vpgf/contributed-plugins/92)* status: 22 of 26 files reviewed, 9 unresolved discussions (waiting on @aparujan and @jolevesq)

___
*[range-slider/README.md, line 50 at r1](https://reviewable.io/reviews/fgpv-vpgf/contributed-plugins/92#-MIU2Kol3gXL7JbTogGy:-MIV6VEM-BT3VjRXBXJC:b-896fix) ([raw file](https://github.com/fgpv-vpgf/contributed-plugins/blob/97b448af0bd25f8a32f7ee2636c99c3f1439f503/range-slider/README.md#L50)):*
<details><summary><i>Previously, aparujan (Akhil Parujanwala) wrote…</i></summary><blockquote>

extra space after "data"
</blockquote></details>

Done.
___
*[range-slider/README.md, line 67 at r1](https://reviewable.io/reviews/fgpv-vpgf/contributed-plugins/92#-MIU2kndD_5iwLqNDBS6:-MIV6nznCeOguu9kQMkB:b-yh7l0p) ([raw file](https://github.com/fgpv-vpgf/contributed-plugins/blob/97b448af0bd25f8a32f7ee2636c99c3f1439f503/range-slider/README.md#L67)):*
<details><summary><i>Previously, aparujan (Akhil Parujanwala) wrote…</i></summary><blockquote>

Possibly typo, "Whit", I belive it could be "With"?
</blockquote></details>

With is good, means avec
___
*[range-slider/src/slider-bar.ts, line 111 at r1](https://reviewable.io/reviews/fgpv-vpgf/contributed-plugins/92#-MIU433N94VAtAn9fSaB:-MIV7CXO1U0LFJzRjc-a:b-896fix) ([raw file](https://github.com/fgpv-vpgf/contributed-plugins/blob/97b448af0bd25f8a32f7ee2636c99c3f1439f503/range-slider/src/slider-bar.ts#L111)):*
<details><summary><i>Previously, aparujan (Akhil Parujanwala) wrote…</i></summary><blockquote>

Perhaps use a carriage return or leave the space as it such that the loop is easier to read.
</blockquote></details>

Done.
___
*[range-slider/src/slider-bar.ts, line 225 at r1](https://reviewable.io/reviews/fgpv-vpgf/contributed-plugins/92#-MIU4T-cCF-I4rayUut7:-MIV7J2q8yEwsPE4NHHG:b-896fix) ([raw file](https://github.com/fgpv-vpgf/contributed-plugins/blob/97b448af0bd25f8a32f7ee2636c99c3f1439f503/range-slider/src/slider-bar.ts#L225)):*
<details><summary><i>Previously, aparujan (Akhil Parujanwala) wrote…</i></summary><blockquote>

extra space
</blockquote></details>

Done.
___
*[range-slider/src/slider-bar.ts, line 234 at r1](https://reviewable.io/reviews/fgpv-vpgf/contributed-plugins/92#-MIU4W8m3BJrBmF-wWz_:-MIV7SDM2EkamK0NhZWa:b-896fix) ([raw file](https://github.com/fgpv-vpgf/contributed-plugins/blob/97b448af0bd25f8a32f7ee2636c99c3f1439f503/range-slider/src/slider-bar.ts#L234)):*
<details><summary><i>Previously, aparujan (Akhil Parujanwala) wrote…</i></summary><blockquote>

extra space
</blockquote></details>

Done.
___
*[range-slider/src/slider-bar.ts, line 390 at r1](https://reviewable.io/reviews/fgpv-vpgf/contributed-plugins/92#-MIU4eGVCaDYJ2jTCG-o:-MIV87keEEdYOSFRfTYP:b-896fix) ([raw file](https://github.com/fgpv-vpgf/contributed-plugins/blob/97b448af0bd25f8a32f7ee2636c99c3f1439f503/range-slider/src/slider-bar.ts#L390)):*
<details><summary><i>Previously, aparujan (Akhil Parujanwala) wrote…</i></summary><blockquote>

extra space
</blockquote></details>

Done.
___
*[range-slider/src/slider-bar.ts, line 532 at r1](https://reviewable.io/reviews/fgpv-vpgf/contributed-plugins/92#-MIU4kRu-OKr2_wZhDGY:-MIV8GgTD6COIZqJ3XyX:b-896fix) ([raw file](https://github.com/fgpv-vpgf/contributed-plugins/blob/97b448af0bd25f8a32f7ee2636c99c3f1439f503/range-slider/src/slider-bar.ts#L532)):*
<details><summary><i>Previously, aparujan (Akhil Parujanwala) wrote…</i></summary><blockquote>

extra space
</blockquote></details>

Done.
___
*[range-slider/src/samples/slider-dual-static-config.json, line 52 at r1](https://reviewable.io/reviews/fgpv-vpgf/contributed-plugins/92#-MIU6uf80kIax2F4m92M:-MIV8rbv0azomMY5zfRJ:b-896fix) ([raw file](https://github.com/fgpv-vpgf/contributed-plugins/blob/97b448af0bd25f8a32f7ee2636c99c3f1439f503/range-slider/src/samples/slider-dual-static-config.json#L52)):*
<details><summary><i>Previously, aparujan (Akhil Parujanwala) wrote…</i></summary><blockquote>

this as 'a' place holder. * put a space after the 'a' and before 'place'
</blockquote></details>

Done.

**Review by jolevesq — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/fgpv-vpgf/contributed-plugins/92)* status: 22 of 26 files reviewed, 9 unresolved discussions (waiting on @aparujan)

___
*[range-slider/src/slider-manager.ts, line 72 at r1](https://reviewable.io/reviews/fgpv-vpgf/contributed-plugins/92#-MIU6JA39SfAyZKhVV6R:-MIV9iIYDSHHtmOm2UNw:b-896fix) ([raw file](https://github.com/fgpv-vpgf/contributed-plugins/blob/97b448af0bd25f8a32f7ee2636c99c3f1439f503/range-slider/src/slider-manager.ts#L72)):*
<details><summary><i>Previously, aparujan (Akhil Parujanwala) wrote…</i></summary><blockquote>

extra space
</blockquote></details>

Done.

**Comment by aparujan** [comment]
___
*[range-slider/README.md, line 67 at r1](https://reviewable.io/reviews/fgpv-vpgf/contributed-plugins/92#-MIU2kndD_5iwLqNDBS6:-MIVCtCW-ZIGdrxpMFOb:b-4cbwf4) ([raw file](https://github.com/fgpv-vpgf/contributed-plugins/blob/97b448af0bd25f8a32f7ee2636c99c3f1439f503/range-slider/README.md#L67)):*
<details><summary><i>Previously, jolevesq (Johann Levesque) wrote…</i></summary><blockquote>

With is good, means avec
</blockquote></details>

lol yah.
Actually , I still think there's a typo there though:   range type and dynamic limit. Whit the other type of range and limit, <- Perhaps "With" as opposed to "Whit".

**Comment by aparujan** [comment]
:lgtm:

**Review by aparujan — COMMENTED** [review]
> Reviewed 4 of 4 files at r2.
> *[Reviewable](https://reviewable.io/reviews/fgpv-vpgf/contributed-plugins/92)* status: all files reviewed, 1 unresolved discussion (waiting on @jolevesq)

**Review by jolevesq — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/fgpv-vpgf/contributed-plugins/92)* status: 25 of 26 files reviewed, 1 unresolved discussion (waiting on @aparujan)

___
*[range-slider/README.md, line 67 at r1](https://reviewable.io/reviews/fgpv-vpgf/contributed-plugins/92#-MIU2kndD_5iwLqNDBS6:-MIVEVi41Kh_kV_cZ0rk:boawd1a) ([raw file](https://github.com/fgpv-vpgf/contributed-plugins/blob/97b448af0bd25f8a32f7ee2636c99c3f1439f503/range-slider/README.md#L67)):*
<details><summary><i>Previously, aparujan (Akhil Parujanwala) wrote…</i></summary><blockquote>

lol yah.
Actually , I still think there's a typo there though:   range type and dynamic limit. Whit the other type of range and limit, <- Perhaps "With" as opposed to "Whit".
</blockquote></details>

You are right, I looked at the wrong with :-)

**Review by jolevesq — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/fgpv-vpgf/contributed-plugins/92)* status: 25 of 26 files reviewed, 1 unresolved discussion (waiting on @aparujan)

___
*[range-slider/README.md, line 67 at r1](https://reviewable.io/reviews/fgpv-vpgf/contributed-plugins/92#-MIU2kndD_5iwLqNDBS6:-MIVEa7H9rbBgNiYL6Cu:b-896fix) ([raw file](https://github.com/fgpv-vpgf/contributed-plugins/blob/97b448af0bd25f8a32f7ee2636c99c3f1439f503/range-slider/README.md#L67)):*
<details><summary><i>Previously, jolevesq (Johann Levesque) wrote…</i></summary><blockquote>

You are right, I looked at the wrong with :-)
</blockquote></details>

Done.

**Review by aparujan — COMMENTED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/fgpv-vpgf/contributed-plugins/92#-:-MIVEquJ1p_4Sy3RM2ZN:bnfp4nl)* status: 25 of 26 files reviewed, all discussions resolved (waiting on @aparujan)

**Review by aparujan — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/fgpv-vpgf/contributed-plugins/92#-:-MIVEs0qBj56rHmrZfmD:bnfp4nl)* status: 25 of 26 files reviewed, all discussions resolved (waiting on @aparujan)

**Review by aparujan — COMMENTED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/fgpv-vpgf/contributed-plugins/92#-:-MIVHrHG7x4tQttrd3ci:bnfp4nl)* status: 25 of 26 files reviewed, all discussions resolved (waiting on @aparujan)

**Review by aparujan — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/fgpv-vpgf/contributed-plugins/92#-:-MIVI5bKDf0VTkszf1GZ:bnfp4nl)* status: 25 of 26 files reviewed, all discussions resolved (waiting on @aparujan)

**Review by aparujan — APPROVED** [review]
> Reviewed 1 of 26 files at r1, 1 of 1 files at r3.
> *[Reviewable](https://reviewable.io/reviews/fgpv-vpgf/contributed-plugins/92)* status: :shipit: complete! all files reviewed, all discussions resolved

**Pull request merged**
